# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0.4  # oldest supported in Project.toml
  - 1.1
  - 1.2
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
